network:
  ethernets:
    enp0s3:
      # Bridge adapter — access from host machine
      dhcp4: true
    enp0s8:
      # Internal network "clientnet" — communication with VM B
      dhcp4: no
      addresses: [192.168.8.10/24]
      gateway4: 192.168.8.1
  version: 2
